//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceTracker.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and edit jobs.
        /// </summary>
        internal static string AddAndEditJobs {
            get {
                return ResourceManager.GetString("AddAndEditJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workshift .
        /// </summary>
        internal static string AddWorkshiftBtn {
            get {
                return ResourceManager.GetString("AddWorkshiftBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Tracker.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyNameLabel {
            get {
                return ResourceManager.GetString("CompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        internal static string CreateJob {
            get {
                return ResourceManager.GetString("CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashoard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Jobs.
        /// </summary>
        internal static string GetJobsBtn {
            get {
                return ResourceManager.GetString("GetJobsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Type.
        /// </summary>
        internal static string HireType {
            get {
                return ResourceManager.GetString("HireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday pay.
        /// </summary>
        internal static string HolidayPay {
            get {
                return ResourceManager.GetString("HolidayPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Rate.
        /// </summary>
        internal static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Jobs .
        /// </summary>
        internal static string JobsTitle {
            get {
                return ResourceManager.GetString("JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Hours.
        /// </summary>
        internal static string LogHours {
            get {
                return ResourceManager.GetString("LogHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshifts.
        /// </summary>
        internal static string LogHoursTitle {
            get {
                return ResourceManager.GetString("LogHoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paycheck.
        /// </summary>
        internal static string Paycheck {
            get {
                return ResourceManager.GetString("Paycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare!.
        /// </summary>
        internal static string PaycheckCompareButton {
            get {
                return ResourceManager.GetString("PaycheckCompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paycheck Details.
        /// </summary>
        internal static string PaycheckDetails {
            get {
                return ResourceManager.GetString("PaycheckDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month 1-12.
        /// </summary>
        internal static string PaycheckMonthLabel {
            get {
                return ResourceManager.GetString("PaycheckMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paycheck.
        /// </summary>
        internal static string PaycheckTitle {
            get {
                return ResourceManager.GetString("PaycheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. shopassistent.
        /// </summary>
        internal static string PlaceholderTitle {
            get {
                return ResourceManager.GetString("PlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Job.
        /// </summary>
        internal static string RegisterJobBtn {
            get {
                return ResourceManager.GetString("RegisterJobBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string RegisterPhone {
            get {
                return ResourceManager.GetString("RegisterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student grant.
        /// </summary>
        internal static string StudentGrant {
            get {
                return ResourceManager.GetString("StudentGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplement Detail.
        /// </summary>
        internal static string SubPayAddButton {
            get {
                return ResourceManager.GetString("SubPayAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string SubPayAmount {
            get {
                return ResourceManager.GetString("SubPayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string SubPayDayNumber {
            get {
                return ResourceManager.GetString("SubPayDayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter End Time.
        /// </summary>
        internal static string SubPayEndTime {
            get {
                return ResourceManager.GetString("SubPayEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Start Time.
        /// </summary>
        internal static string SubPayStartTime {
            get {
                return ResourceManager.GetString("SubPayStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement Details.
        /// </summary>
        internal static string SubPayTitle {
            get {
                return ResourceManager.GetString("SubPayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Card.
        /// </summary>
        internal static string TaxCard {
            get {
                return ResourceManager.GetString("TaxCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Pay.
        /// </summary>
        internal static string VacPayTitle {
            get {
                return ResourceManager.GetString("VacPayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshift endtime.
        /// </summary>
        internal static string WorkshiftEndtime {
            get {
                return ResourceManager.GetString("WorkshiftEndtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshift starttime.
        /// </summary>
        internal static string WorkshiftStarttime {
            get {
                return ResourceManager.GetString("WorkshiftStarttime", resourceCulture);
            }
        }
    }
}
